CREATE TABLE "users" (
  "id_users" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "user_course" (
  "id_user_course" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_users" int NOT NULL,
  "id_courses" int NOT NULL
);

CREATE TABLE "courses" (
  "id_courses" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "description" varchar(30) NOT NULL,
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL,
  "id_categories" int NOT NULL
);

CREATE TABLE "course_video" (
  "id_course_video" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "url" varchar(50) NOT NULL,
  "id_courses" int NOT NULL
);

CREATE TABLE "categories" (
  "id_categories" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categories_name" varchar(25) NOT NULL
);

CREATE TABLE "roles" (
  "id_roles" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "level" (
  "id_level" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_level" varchar(25) NOT NULL
);

CREATE TABLE "teacher" (
  "id_teacher" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_teacher" varchar(25) NOT NULL
);

CREATE TABLE "teacher_courses" (
  "id_teacher_courses" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_teacher" int NOT NULL,
  "id_courses" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id_roles");

ALTER TABLE "user_course" ADD FOREIGN KEY ("id_users") REFERENCES "users" ("id_users");

ALTER TABLE "user_course" ADD FOREIGN KEY ("id_courses") REFERENCES "courses" ("id_courses");

ALTER TABLE "course_video" ADD FOREIGN KEY ("id_courses") REFERENCES "courses" ("id_courses");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id_categories");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id_level");

ALTER TABLE "teacher_courses" ADD FOREIGN KEY ("id_teacher") REFERENCES "teacher" ("id_teacher");

ALTER TABLE "teacher_courses" ADD FOREIGN KEY ("id_courses") REFERENCES "courses" ("id_courses");




INSERT INTO "roles"(name) VALUES ('student');

INSERT INTO "roles"(name) VALUES  ('teacher');

INSERT INTO "roles"(name) VALUES ('admin');


INSERT INTO "level"(nom_level) VALUES ('principiante');

INSERT INTO "level"(nom_level) VALUES  ('medio');

INSERT INTO "level"(nom_level) VALUES ('avanzado');




INSERT INTO "teacher"(nom_teacher) VALUES ('Juan Andrade');

INSERT INTO "teacher"(nom_teacher) VALUES  ('Camilo Torres');

INSERT INTO "teacher"(nom_teacher) VALUES ('Agustin Rodriguez');




INSERT INTO "categories"(categories_name) VALUES ('Technology');

INSERT INTO "categories"(categories_name) VALUES  ('Business');

INSERT INTO "categories"(categories_name) VALUES ('Marketing');


INSERT INTO "courses"(title, description, id_level, id_categories) VALUES ('data', 'learn about data', 1, 1);

INSERT INTO "courses"(title, description, id_level, id_categories) VALUES  ('financial', 'learn about financial', 2, 1);

INSERT INTO "courses"(title, description, id_level, id_categories) VALUES ('Seo', 'learn about Seo', 3, 3);



INSERT INTO "teacher_courses"(id_teacher, id_courses) VALUES (1, 3);

INSERT INTO "teacher_courses"(id_teacher, id_courses) VALUES  (2, 2);

INSERT INTO "teacher_courses"(id_teacher, id_courses) VALUES (3, 4);



INSERT INTO "course_video"(title, url, id_courses) VALUES ('science data', 'data/science.com', 2);

INSERT INTO "course_video"(title, url, id_courses) VALUES  ('web succeded', 'youtube.com/web/r',4);

INSERT INTO "course_video"(title, url, id_courses) VALUES ('rich today', 'youtube.com/rich/r',3);



INSERT INTO "users"(name, email, password, age, id_roles) VALUES ('Eduardo','e@gmail.com', 'e123',22, 1);

INSERT INTO "users"(name, email, password, age, id_roles) VALUES  ('Ian', 'ian@gmail.com', 'i123', 27, 2);

INSERT INTO "users"(name, email, password, age, id_roles) VALUES ('Luis', 'l@gmail.com', 'l123', 40, 3);



INSERT INTO "user_course"(id_users, id_courses) VALUES (1,3);

INSERT INTO "user_course"(id_users, id_courses) VALUES  (2,2);

INSERT INTO "user_course"(id_users, id_courses) VALUES (3,4);